name: Build for multiple SDK versions

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        # Builds for Debug and Release configurations
        configuration: [Debug, Release]
        # Builds for Ubuntu, Windows, and macOS
        os: [ubuntu-latest, windows-latest, macOS-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      # setup .NET per the repo global.json
      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      # setup .NET per test session
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.x
            9.x

      # let's make sure we're on the version we think we are.
      - name: Announce .NET version
        run: dotnet --info

      - name: Restore tools
        run: dotnet tool restore

      - name: Run build and test
        run: dotnet run --project build

      - name: Archive test results
        uses: actions/upload-artifact@v3

        with:
          name: test-results
          path: test/**/TestResults/*.trx
